# Generated by Django 4.2.7 on 2024-02-02 16:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default/no_image.png', upload_to=users.models.CustomUser.image_upload_to),
        ),
    ]
