# Generated by Django 4.2.7 on 2024-02-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_articleseries_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='articleseries',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Series'},
        ),
    ]
