# Generated by Django 4.2.7 on 2024-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_article_options_alter_articleseries_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='Default'),
        ),
    ]
